(function () {
    "use strict";

    angular.module('app')
        .service('teamDataService', function ($http) {

            this.registerTeam = function (newTeam) {
                console.log(newTeam);
                $http.post("/api/registerTeam", newTeam).success(function () { alert("Registration Successful") }).error(function () { alert("Registration Failed, Please contact us") });
            };

            this.teamData = [
                {
                    "id": 10,
                    "teamname": " Monument Men",
                    "company": "Memorial Monuments",
                    "division": "preNBA",
                    "companynum": "2085893128",
                    "email": "jpyounis@yahoo.com",
                    "member1": "Dayson Hunter",
                    "member2": "Tregan Younis",
                    "member3": "Ezra Parrish",
                    "member4": "Eli Parrish",
                    "shirtsize1": "yl",
                    "shirtsize2": "yl",
                    "shirtsize3": "yl",
                    "shirtsize4": "yl",
                    "creationdate": "2015-07-01 17:34:44"
                },
                {
                    "id": 11,
                    "teamname": "2 and out",
                    "company": "1A HEATING AND COOLING",
                    "division": "comp",
                    "companynum": "2084079129",
                    "email": "1aheatingandcooling@gmail.com",
                    "member1": "luke navarez",
                    "member2": "travis lara",
                    "member3": "tyler clark",
                    "member4": "chago ramirez",
                    "shirtsize1": "l",
                    "shirtsize2": "l",
                    "shirtsize3": "xl",
                    "shirtsize4": "xxl",
                    "creationdate": "2015-07-05 21:36:24"
                },
                {
                    "id": 12,
                    "teamname": "ICCU Eagles",
                    "company": "Idaho Central Credit Union",
                    "division": "bill",
                    "companynum": "2086378367",
                    "email": "amccabe@iccu.com",
                    "member1": "Jake Dyer",
                    "member2": "Phillip Johnson",
                    "member3": "Darryl Apel",
                    "member4": "Aaron McCabe",
                    "shirtsize1": "l",
                    "shirtsize2": "l",
                    "shirtsize3": "xxl",
                    "shirtsize4": "xxl",
                    "creationdate": "2015-07-14 17:20:13"
                },
                {
                    "id": 13,
                    "teamname": "ICCU",
                    "company": "Idaho Central Credit Union",
                    "division": "comp",
                    "companynum": "",
                    "email": "",
                    "member1": "Jared Erickson",
                    "member2": "Storm Shelley",
                    "member3": "Nick Winters",
                    "member4": "Rob Martindale",
                    "shirtsize1": "l",
                    "shirtsize2": "l",
                    "shirtsize3": "xl",
                    "shirtsize4": "l",
                    "creationdate": "2015-07-15 17:33:14"
                },
                {
                    "id": 14,
                    "teamname": "Ballers",
                    "company": "Ambulatory Foot and Ankle Clinic",
                    "division": "preNBA",
                    "companynum": "208-760-9563",
                    "email": "godfrey.koree@gmail.com",
                    "member1": "Ezra Godfrey",
                    "member2": "Jayden Wright",
                    "member3": "Daniel Neal",
                    "member4": "Beau Brower",
                    "shirtsize1": "ym",
                    "shirtsize2": "s",
                    "shirtsize3": "yl",
                    "shirtsize4": "ym",
                    "creationdate": "2015-07-20 21:06:46"
                },
                {
                    "id": 15,
                    "teamname": "Jaguars ",
                    "company": "",
                    "division": "comp",
                    "companynum": "",
                    "email": "parrian@isu.edu",
                    "member1": "Ian Parrish",
                    "member2": "Derek Knapp",
                    "member3": "Cole Ashby",
                    "member4": "Chris Randell ",
                    "shirtsize1": "xl",
                    "shirtsize2": "l",
                    "shirtsize3": "l",
                    "shirtsize4": "l",
                    "creationdate": "2015-07-24 19:09:47"
                },
                {
                    "id": 16,
                    "teamname": "U15 Elite",
                    "company": "",
                    "division": "keegan",
                    "companynum": "",
                    "email": "",
                    "member1": "Jack Thompson",
                    "member2": "Mason Price",
                    "member3": "Reydavid Venegas",
                    "member4": "",
                    "shirtsize1": "xl",
                    "shirtsize2": "xl",
                    "shirtsize3": "l",
                    "shirtsize4": "",
                    "creationdate": "2015-07-28 19:53:14"
                },
                {
                    "id": 17,
                    "teamname": "Spurs",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "jacktren@isu.edu",
                    "member1": "Coulson Jackman",
                    "member2": "Nicholas  Price",
                    "member3": "Gage Leslie",
                    "member4": "Drake Johnson",
                    "shirtsize1": "s",
                    "shirtsize2": "s",
                    "shirtsize3": "s",
                    "shirtsize4": "s",
                    "creationdate": "2015-07-29 18:23:42"
                },
                {
                    "id": 18,
                    "teamname": "New Day Crew",
                    "company": "New Day Products",
                    "division": "preNBA",
                    "companynum": "208-206-2766",
                    "email": "sparkdc123@gmail.com",
                    "member1": "Zachary Park",
                    "member2": "Jett Baker",
                    "member3": "Trim Tolman",
                    "member4": "Bode Baker",
                    "shirtsize1": "s",
                    "shirtsize2": "s",
                    "shirtsize3": "yl",
                    "shirtsize4": "yl",
                    "creationdate": "2015-07-30 20:51:02"
                },
                {
                    "id": 19,
                    "teamname": "B",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "",
                    "member1": "D",
                    "member2": "D",
                    "member3": "G",
                    "member4": "",
                    "shirtsize1": "ys",
                    "shirtsize2": "ys",
                    "shirtsize3": "ys",
                    "shirtsize4": "",
                    "creationdate": "2015-08-01 01:34:53"
                },
                {
                    "id": 5,
                    "teamname": "Awesome4",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "jpyounis@yahoo.com",
                    "member1": "Zerek Younis",
                    "member2": "Max Parrish",
                    "member3": "Josiah Parrish",
                    "member4": "Spencer Parrish",
                    "shirtsize1": "ym",
                    "shirtsize2": "ym",
                    "shirtsize3": "yl",
                    "shirtsize4": "yl",
                    "creationdate": "2015-07-01 17:23:48"
                },
                {
                    "id": 6,
                    "teamname": "Squad",
                    "company": "",
                    "division": "rossa",
                    "companynum": "",
                    "email": "janmccarthyhhs@gmail.com",
                    "member1": "Cassidee Whitehead",
                    "member2": "Sevana Spoklie",
                    "member3": "Makenna Baker",
                    "member4": "Allie Thayne",
                    "shirtsize1": "m",
                    "shirtsize2": "s",
                    "shirtsize3": "s",
                    "shirtsize4": "xl",
                    "creationdate": "2015-07-10 16:34:55"
                },
                {
                    "id": 7,
                    "teamname": " Legends",
                    "company": "",
                    "division": "comp",
                    "companynum": "",
                    "email": "devellewright@gmail.com",
                    "member1": "Develle ",
                    "member2": "Nealand",
                    "member3": "Noah",
                    "member4": "Eddie",
                    "shirtsize1": "l",
                    "shirtsize2": "m",
                    "shirtsize3": "m",
                    "shirtsize4": "l",
                    "creationdate": "2015-07-11 05:42:38"
                },
                {
                    "id": 8,
                    "teamname": "Eagles of Idaho Central",
                    "company": "",
                    "division": "bill",
                    "companynum": "",
                    "email": "jrudd@iccu.com",
                    "member1": "Jeff Rudd",
                    "member2": "Tommy Butler",
                    "member3": "Nick Riley",
                    "member4": "Derek Mathews",
                    "shirtsize1": "xl",
                    "shirtsize2": "xl",
                    "shirtsize3": "l",
                    "shirtsize4": "xxl",
                    "creationdate": "2015-07-16 10:52:53"
                },
                {
                    "id": 9,
                    "teamname": "crusaders",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "ringer3@cableone.net",
                    "member1": "sarah hiller",
                    "member2": "emma wedler",
                    "member3": "carmen mendez",
                    "member4": "lily maheras",
                    "shirtsize1": "s",
                    "shirtsize2": "m",
                    "shirtsize3": "s",
                    "shirtsize4": "m",
                    "creationdate": "2015-07-21 02:14:22"
                },
                {
                    "id": 10,
                    "teamname": "diamondbacks",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "ringer3@cableone.net",
                    "member1": "warren hiller",
                    "member2": "conner magnuson",
                    "member3": "chris wedler",
                    "member4": "cody smoot",
                    "shirtsize1": "m",
                    "shirtsize2": "m",
                    "shirtsize3": "m",
                    "shirtsize4": "m",
                    "creationdate": "2015-07-21 03:32:04"
                },
                {
                    "id": 11,
                    "teamname": "HS Crusaders 5th",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "rmagnuson@msvmgroup.com",
                    "member1": "Braden Magnuson",
                    "member2": "Joe Behrend",
                    "member3": "Ryan Foltz",
                    "member4": "Silas Wills",
                    "shirtsize1": "yl",
                    "shirtsize2": "yl",
                    "shirtsize3": "yl",
                    "shirtsize4": "yl",
                    "creationdate": "2015-07-21 18:49:40"
                },
                {
                    "id": 12,
                    "teamname": "Da Bulls",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "janmccarthyhhs@gmail,com",
                    "member1": "Lucas Whitehead",
                    "member2": "Nash Harding",
                    "member3": "Raimon Barella",
                    "member4": "Ryan Payne",
                    "shirtsize1": "s",
                    "shirtsize2": "s",
                    "shirtsize3": "yl",
                    "shirtsize4": "s",
                    "creationdate": "2015-07-22 10:12:02"
                },
                {
                    "id": 13,
                    "teamname": "Blaze",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "dshaneanderson@gmail.com",
                    "member1": "Fischer ",
                    "member2": "Lucas",
                    "member3": "Adam",
                    "member4": "Jackson",
                    "shirtsize1": "m",
                    "shirtsize2": "yl",
                    "shirtsize3": "yl",
                    "shirtsize4": "m",
                    "creationdate": "2015-07-22 18:33:40"
                },
                {
                    "id": 14,
                    "teamname": "Poky Girls",
                    "company": "",
                    "division": "keegan",
                    "companynum": "",
                    "email": "jacktren@isu.edu",
                    "member1": "Kate Jackman ",
                    "member2": "Alysa Spillett",
                    "member3": "Riley Pearson",
                    "member4": "Destiny Harris",
                    "shirtsize1": "m",
                    "shirtsize2": "s",
                    "shirtsize3": "m",
                    "shirtsize4": "l",
                    "creationdate": "2015-07-22 22:01:54"
                },
                {
                    "id": 15,
                    "teamname": "Fluffy Bunnies",
                    "company": "",
                    "division": "comp",
                    "companynum": "",
                    "email": "wildeb5@gmail.com",
                    "member1": "Brian Wilde",
                    "member2": "Justin Walls",
                    "member3": "Ryan Ray",
                    "member4": "John Ward",
                    "shirtsize1": "l",
                    "shirtsize2": "l",
                    "shirtsize3": "l",
                    "shirtsize4": "xl",
                    "creationdate": "2015-07-24 10:41:37"
                },
                {
                    "id": 16,
                    "teamname": "Undertow",
                    "company": "",
                    "division": "bill",
                    "companynum": "",
                    "email": "jensengraham.ken@gmail.com",
                    "member1": "Ken Graham",
                    "member2": "Travis Highland",
                    "member3": "Kevin Barber",
                    "member4": "Benjamin Leake",
                    "shirtsize1": "xl",
                    "shirtsize2": "m",
                    "shirtsize3": "xl",
                    "shirtsize4": "l",
                    "creationdate": "2015-07-24 18:54:08"
                },
                {
                    "id": 17,
                    "teamname": "Zions Bank Executive Banking",
                    "company": "",
                    "division": "comp",
                    "companynum": "",
                    "email": "velasquez941@live.com",
                    "member1": "Adam Velasquez",
                    "member2": "Nick Hansen",
                    "member3": "Robbie Bybee",
                    "member4": "Jordan Hart",
                    "shirtsize1": "xl",
                    "shirtsize2": "xxl",
                    "shirtsize3": "l",
                    "shirtsize4": "l",
                    "creationdate": "2015-07-25 10:44:09"
                },
                {
                    "id": 18,
                    "teamname": "Guardians of the Galaxy",
                    "company": "",
                    "division": "keegan",
                    "companynum": "",
                    "email": "pseswilliams@juno.com",
                    "member1": "Seth Williams",
                    "member2": "Tucker Hough",
                    "member3": "Parker Williams",
                    "member4": "",
                    "shirtsize1": "l",
                    "shirtsize2": "l",
                    "shirtsize3": "l",
                    "shirtsize4": "",
                    "creationdate": "2015-07-26 00:36:47"
                },
                {
                    "id": 19,
                    "teamname": "3 Amigos",
                    "company": "",
                    "division": "liam",
                    "companynum": "",
                    "email": "pseswilliams@juno.com",
                    "member1": "Eli Williams",
                    "member2": "Titan Fleischmann",
                    "member3": "Bruin Fleischamnn",
                    "member4": "",
                    "shirtsize1": "yl",
                    "shirtsize2": "xl",
                    "shirtsize3": "l",
                    "shirtsize4": "",
                    "creationdate": "2015-07-26 14:26:55"
                },
                {
                    "id": 20,
                    "teamname": "Pink Mamba",
                    "company": "",
                    "division": "rossb",
                    "companynum": "",
                    "email": "Apmarsh12@gmail.com",
                    "member1": "April smith",
                    "member2": "Cerissa Honena ",
                    "member3": "Taitum Degarmo",
                    "member4": "",
                    "shirtsize1": "l",
                    "shirtsize2": "l",
                    "shirtsize3": "l",
                    "shirtsize4": "",
                    "creationdate": "2015-07-26 20:17:26"
                },
                {
                    "id": 21,
                    "teamname": "DirectCom 1",
                    "company": "",
                    "division": "bill",
                    "companynum": "",
                    "email": "michael@directcom.com",
                    "member1": "R. Michael Parrish",
                    "member2": "Daniel Parrish",
                    "member3": "a",
                    "member4": "b",
                    "shirtsize1": "xl",
                    "shirtsize2": "xl",
                    "shirtsize3": "xl",
                    "shirtsize4": "xl",
                    "creationdate": "2015-07-27 11:53:36"
                },
                {
                    "id": 22,
                    "teamname": "DirectCom Rockland Boys",
                    "company": "",
                    "division": "keegan",
                    "companynum": "",
                    "email": "michael@directcom.com",
                    "member1": "Rodney Payton Parrish",
                    "member2": "Spencer Permann",
                    "member3": "Zakery Smith",
                    "member4": "Paxton Boyer",
                    "shirtsize1": "m",
                    "shirtsize2": "l",
                    "shirtsize3": "l",
                    "shirtsize4": "l",
                    "creationdate": "2015-07-27 11:57:32"
                },
                {
                    "id": 23,
                    "teamname": "DirectCom Rockland Girls",
                    "company": "",
                    "division": "rossa",
                    "companynum": "",
                    "email": "michael@directcom.com",
                    "member1": "Eryn Parrish",
                    "member2": "Evelyn Hull",
                    "member3": "Madalynn Permann",
                    "member4": "Charlotte Wilson",
                    "shirtsize1": "m",
                    "shirtsize2": "m",
                    "shirtsize3": "s",
                    "shirtsize4": "s",
                    "creationdate": "2015-07-27 12:01:14"
                },
                {
                    "id": 24,
                    "teamname": "Indians",
                    "company": "",
                    "division": "keegan",
                    "companynum": "",
                    "email": "plyhrd24@yahoo.com",
                    "member1": "Kobi Gardea",
                    "member2": "Jaden Brown",
                    "member3": "Zach Jensen",
                    "member4": "Jeremiah Kempworth",
                    "shirtsize1": "l",
                    "shirtsize2": "l",
                    "shirtsize3": "xl",
                    "shirtsize4": "xxl",
                    "creationdate": "2015-07-27 15:11:13"
                },
                {
                    "id": 25,
                    "teamname": "FCancer",
                    "company": "",
                    "division": "bill",
                    "companynum": "",
                    "email": "Clachance77@yahoo.com",
                    "member1": "Troy LaChance ",
                    "member2": "Matt lamunyon ",
                    "member3": "Jimmy Tackett",
                    "member4": "",
                    "shirtsize1": "xl",
                    "shirtsize2": "xl",
                    "shirtsize3": "xl",
                    "shirtsize4": "ys",
                    "creationdate": "2015-07-27 16:11:40"
                },
                {
                    "id": 26,
                    "teamname": "Bulls",
                    "company": "",
                    "division": "liam",
                    "companynum": "",
                    "email": "kgardea31@yahoo.com",
                    "member1": "Kassidy Gardea",
                    "member2": "Harley Jackson",
                    "member3": "Kennadie Phillips",
                    "member4": "Jacqueline Christensen",
                    "shirtsize1": "s",
                    "shirtsize2": "s",
                    "shirtsize3": "m",
                    "shirtsize4": "m",
                    "creationdate": "2015-07-27 17:34:19"
                },
                {
                    "id": 27,
                    "teamname": "Rockets",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "kgardea31@yahoo.com",
                    "member1": "Kyleigh Gardea",
                    "member2": "Anna Campbell",
                    "member3": "Marissa Mauger",
                    "member4": "Ryan Pokibro",
                    "shirtsize1": "yl",
                    "shirtsize2": "yl",
                    "shirtsize3": "m",
                    "shirtsize4": "ym",
                    "creationdate": "2015-07-27 17:37:29"
                },
                {
                    "id": 28,
                    "teamname": "U15 Elite",
                    "company": "",
                    "division": "keegan",
                    "companynum": "",
                    "email": "bradlandes@gmail.com",
                    "member1": "Jack Thompson",
                    "member2": "Mason Price",
                    "member3": "Reydavid Venegas",
                    "member4": "",
                    "shirtsize1": "xl",
                    "shirtsize2": "xl",
                    "shirtsize3": "l",
                    "shirtsize4": "",
                    "creationdate": "2015-07-27 19:24:26"
                },
                {
                    "id": 29,
                    "teamname": "TWolves",
                    "company": "",
                    "division": "liam",
                    "companynum": "",
                    "email": "snad@cableone.net",
                    "member1": "Dylan Seeley",
                    "member2": "Jaxon Sorenson",
                    "member3": "Jack Groberg",
                    "member4": "",
                    "shirtsize1": "m",
                    "shirtsize2": "m",
                    "shirtsize3": "s",
                    "shirtsize4": "",
                    "creationdate": "2015-07-28 09:35:54"
                },
                {
                    "id": 30,
                    "teamname": "Century",
                    "company": "",
                    "division": "keegan",
                    "companynum": "",
                    "email": "Nsbbballgirl@gmail.com",
                    "member1": "Naomi Behrend ",
                    "member2": "Mckayla Jensen ",
                    "member3": "Emily Packham ",
                    "member4": "Katie Hiller ",
                    "shirtsize1": "m",
                    "shirtsize2": "m",
                    "shirtsize3": "s",
                    "shirtsize4": "s",
                    "creationdate": "2015-07-30 01:05:55"
                },
                {
                    "id": 31,
                    "teamname": "2014 Defending Champs",
                    "company": "",
                    "division": "bill",
                    "companynum": "",
                    "email": "robertpoleki@yahoo.com",
                    "member1": "Robert Poleki",
                    "member2": "Trent Campbell",
                    "member3": "Fritz Zweigart",
                    "member4": "Chad Carr",
                    "shirtsize1": "xxl",
                    "shirtsize2": "xl",
                    "shirtsize3": "xxl",
                    "shirtsize4": "xl",
                    "creationdate": "2015-07-30 13:54:10"
                },
                {
                    "id": 32,
                    "teamname": "Knights",
                    "company": "",
                    "division": "liam",
                    "companynum": "",
                    "email": "AParslow@Spineidaho.org",
                    "member1": "Dalton Parslow",
                    "member2": "Payton Cleaves",
                    "member3": "Isiah Salas",
                    "member4": "",
                    "shirtsize1": "l",
                    "shirtsize2": "l",
                    "shirtsize3": "l",
                    "shirtsize4": "",
                    "creationdate": "2015-07-30 13:55:22"
                },
                {
                    "id": 33,
                    "teamname": "Frito Lay",
                    "company": "",
                    "division": "comp",
                    "companynum": "",
                    "email": "mboyack@q.com",
                    "member1": "Noah Boyack",
                    "member2": "Mark Eskelson",
                    "member3": "Tonu Naetea",
                    "member4": "",
                    "shirtsize1": "xl",
                    "shirtsize2": "l",
                    "shirtsize3": "l",
                    "shirtsize4": "",
                    "creationdate": "2015-07-30 14:22:00"
                },
                {
                    "id": 34,
                    "teamname": "# Amigos",
                    "company": "",
                    "division": "keegan",
                    "companynum": "",
                    "email": "mickey@idlife.org",
                    "member1": "RJ Palmer",
                    "member2": "Payton McCarthy",
                    "member3": "Daxton Carr",
                    "member4": "",
                    "shirtsize1": "m",
                    "shirtsize2": "l",
                    "shirtsize3": "l",
                    "shirtsize4": "",
                    "creationdate": "2015-07-30 19:53:32"
                },
                {
                    "id": 35,
                    "teamname": "The Pelicans",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "Tjjolley14@hotmail.com",
                    "member1": "Trae jolley",
                    "member2": "Kansas Evans ",
                    "member3": "Owen Wilde ",
                    "member4": "",
                    "shirtsize1": "ym",
                    "shirtsize2": "ym",
                    "shirtsize3": "ym",
                    "shirtsize4": "",
                    "creationdate": "2015-07-30 20:59:57"
                },
                {
                    "id": 36,
                    "teamname": "Splash Bros",
                    "company": "",
                    "division": "keegan",
                    "companynum": "",
                    "email": "coltonwadehall@gmail.com ",
                    "member1": "Colton Hall",
                    "member2": "Connor Shippen",
                    "member3": "Duke Golder",
                    "member4": "",
                    "shirtsize1": "l",
                    "shirtsize2": "m",
                    "shirtsize3": "l",
                    "shirtsize4": "",
                    "creationdate": "2015-07-31 11:14:29"
                },
                {
                    "id": 37,
                    "teamname": "Pocatello Athletic Club",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "olsenmisty@gmail.com",
                    "member1": "Jaxon Olsen",
                    "member2": "Jake Jones",
                    "member3": "Ethan Clark",
                    "member4": "Boston Clark",
                    "shirtsize1": "ym",
                    "shirtsize2": "yl",
                    "shirtsize3": "yl",
                    "shirtsize4": "ym",
                    "creationdate": "2015-07-31 15:07:53"
                },
                {
                    "id": 38,
                    "teamname": "HSCS 6",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "kevin.r.marsh@gmail.com",
                    "member1": "Danil Marsh",
                    "member2": "Eric Anderson",
                    "member3": "Sloan Lambson",
                    "member4": "",
                    "shirtsize1": "ys",
                    "shirtsize2": "ys",
                    "shirtsize3": "ys",
                    "shirtsize4": "",
                    "creationdate": "2015-07-31 16:30:03"
                },
                {
                    "id": 39,
                    "teamname": "B",
                    "company": "",
                    "division": "preNBA",
                    "companynum": "",
                    "email": "",
                    "member1": "D",
                    "member2": "D",
                    "member3": "G",
                    "member4": "",
                    "shirtsize1": "ys",
                    "shirtsize2": "ys",
                    "shirtsize3": "ys",
                    "shirtsize4": "",
                    "creationdate": "2015-08-01 01:35:12"
                }
            ]
        });


} ());